/* eslint-disable no-undef */
'use strict';

/**
 * Jest setup: mock the native Nitro module so the compat layer can be tested
 * without a native runtime. `NitroModules.createHybridObject('DeviceInfo')`
 * returns a fixed fake that mirrors the `DeviceInfo` HybridObject surface.
 */

const fakeDeviceInfo = {
  // ---- readonly properties ----
  deviceId: 'iPhone14,2',
  brand: 'Apple',
  model: 'iPhone 13 Pro',
  systemName: 'iOS',
  systemVersion: '17.0',
  deviceType: 'Handset',
  uniqueId: 'FCDBD8EF-62FC-4ECB-B2F5-92C9E79AC7F9',
  manufacturer: 'Apple',
  deviceName: "Tester's iPhone",
  isTablet: false,
  isEmulator: true,
  deviceYearClass: 2023,
  isCameraPresent: true,
  isPinOrFingerprintSet: true,
  isHardwareKeyStoreAvailable: true,
  isLowRamDevice: false,
  isDisplayZoomed: false,
  totalMemory: 6442450944,
  maxMemory: -1,
  totalDiskCapacity: 128849018880,
  startupTime: 1698249600000,
  isLiquidGlassAvailable: false,
  version: '1.2.3',
  buildNumber: '42',
  bundleId: 'com.example.app',
  applicationName: 'Example App',
  readableVersion: '1.2.3.42',
  firstInstallTimeSync: 1698249600000,
  lastUpdateTimeSync: 1698336000000,
  carrierAllowsVOIP: true,
  carrierIsoCountryCode: 'US',
  mobileCountryCode: '310',
  mobileNetworkCode: '260',
  mobileNetworkOperator: '310260',
  systemLanguage: 'en-US',
  supportedAbis: ['arm64'],
  supported32BitAbis: [],
  supported64BitAbis: ['arm64'],
  apiLevel: -1,
  navigationMode: 'unknown',
  systemAvailableFeatures: [],
  supportedMediaTypeList: [],
  serialNumber: 'unknown',
  androidId: 'unknown',
  previewSdkInt: 0,
  securityPatch: 'unknown',
  codename: 'unknown',
  incremental: 'unknown',
  board: 'unknown',
  bootloader: 'unknown',
  device: 'unknown',
  display: 'unknown',
  fingerprint: 'unknown',
  hardware: 'unknown',
  host: 'unknown',
  product: 'unknown',
  tags: 'unknown',
  type: 'unknown',
  baseOs: '',
  radioVersion: 'unknown',
  buildId: 'unknown',
  installerPackageName: 'com.apple.AppStore',
  totalDiskCapacityOld: 128849018880,
  isMouseConnected: false,
  isKeyboardConnected: false,
  hostNames: [],
  isTabletMode: false,

  // ---- sync methods ----
  getHasNotch: () => true,
  getHasDynamicIsland: () => true,
  getIsLandscape: () => false,
  getBrightness: () => 0.8,
  getFontScale: () => 1,
  getUsedMemory: () => 134217728,
  getFreeDiskStorage: () => 51539607552,
  getFreeDiskStorageOld: () => 51539607552,
  getUptime: () => 3600000,
  getBatteryLevel: () => 0.75,
  getPowerState: () => ({
    batteryLevel: 0.75,
    batteryState: 'charging',
    lowPowerMode: false,
  }),
  getIsBatteryCharging: () => true,
  isLowBatteryLevel: threshold => 0.75 < threshold,
  getIpAddressSync: () => '192.168.1.100',
  getMacAddressSync: () => '02:00:00:00:00:00',
  getIsAirplaneMode: () => false,
  getCarrierSync: () => 'Verizon',
  getIsHeadphonesConnected: () => true,
  getIsWiredHeadphonesConnected: () => false,
  getIsBluetoothHeadphonesConnected: () => true,
  getIsLocationEnabled: () => true,
  getAvailableLocationProviders: () => ['gps', 'network'],
  getHasGms: () => false,
  getHasHms: () => false,
  hasSystemFeature: feature => feature === 'android.hardware.camera',
  isSideLoadingEnabled: () => false,
  isDeviceCompromised: () => false,

  // ---- async methods ----
  getFirstInstallTime: () => Promise.resolve(1698249600000),
  getLastUpdateTime: () => Promise.resolve(1698336000000),
  getIpAddress: () => Promise.resolve('192.168.1.100'),
  getMacAddress: () => Promise.resolve('02:00:00:00:00:00'),
  getUserAgent: () => Promise.resolve('Mozilla/5.0 (compat-test)'),
  getCarrier: () => Promise.resolve('Verizon'),
  isHeadphonesConnected: () => Promise.resolve(true),
  isLocationEnabled: () => Promise.resolve(true),
  getDeviceToken: () => Promise.resolve('device-token'),
  syncUniqueId: () => Promise.resolve('FCDBD8EF-62FC-4ECB-B2F5-92C9E79AC7F9'),
  getInstallReferrer: () => Promise.resolve('utm_source=test'),
  verifyDeviceIntegrity: () => Promise.resolve(false),
};

// Expose for assertions in tests.
global.__FAKE_DEVICE_INFO__ = fakeDeviceInfo;

jest.mock('react-native-nitro-modules', () => ({
  NitroModules: {
    createHybridObject: () => global.__FAKE_DEVICE_INFO__,
  },
}));
